# Generated by Django 2.1.7 on 2019-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='project_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_projects.Client'),
        ),
    ]
