# Generated by Django 2.1.7 on 2019-04-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0002_auto_20190330_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_reference',
        ),
    ]
